# Generated by Django 3.1.7 on 2021-03-13 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210313_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchInquiry',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='atk',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='image_src',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sp_atk',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sp_def',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='speed',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userteams',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userteams',
            name='creator_user',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userteams',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userteams',
            name='liked',
            field=models.ManyToManyField(related_name='pokemon_on_team', to='core.Pokemon'),
        ),
        migrations.AddField(
            model_name='userteams',
            name='team_slogan',
            field=models.CharField(default=43, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userteams',
            name='teamname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userteams',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
