# Generated by Django 3.1.7 on 2021-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210313_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_sprite_url',
            field=models.URLField(default='https://cdn.bulbagarden.net/upload/9/98/Missingno_RB.png', max_length=250),
        ),
    ]
